
services:
  mtt:
    image: ghcr.io/buckaroobanzay/mtt:latest
    volumes:
     - "./:/github/workspace"
     - "./output:/root/.minetest/worlds/world"
    environment:
     INPUT_MODNAME: "isogen"
     INPUT_TEST_MODE: "mod"
     INPUT_MAPGEN: "v7"
     INPUT_GIT_GAME_REPO: "https://github.com/minetest/minetest_game"
